Repository pi-hole/docs, pull requests merged in 2021-12, with the labels that each got.

#615 Update fritzbox-de.md
  docs/routers/fritzbox-de.md
Labels: PR: Approved

#610 Add FAQ
  docs/main/faq.md
  mkdocs.yml
Labels: PR: Approval Required

#613 Fix typo
  docs/guides/dns/unbound.md
Labels: PR: Approved

#601 Add enumeration of common dnsmasq warnings
  docs/ftldns/dnsmasq_warn.md
  mkdocs.yml
  package-lock.json
Labels: PR: Approval Required

#607 Add documentation for resource warnings config options
  docs/ftldns/configfile.md
Labels: PR: Approved, For next release

#620 Clarify interface listening behavior
  docs/ftldns/interfaces.md
  docs/images/interface-listening.png
  docs/images/interface-settings.png
Labels: For next release

#621 Add how to increase PHP's memory to FAQ
  docs/main/faq.md
Labels: PR: Approval Required
