Repository pi-hole/docs, pull requests merged in 2021-11, with the labels that each got.

#591 Fix wireguard guide
  docs/guides/vpn/wireguard/client.md
Labels: PR: Approved

#595 Add script for automated Wireguard client generation
  docs/guides/vpn/wireguard/client.md
Labels: enhancement, PR: Approved

#382 Add 'How to fork and rebase'
  docs/guides/github/contributing.md
  docs/guides/github/dco.md
  docs/guides/github/how-to-fork-rebase.md
  mkdocs.yml
Labels: PR: Approved

#602 Fix ugly 'pihole' styling
  docs/extra.css
  mkdocs.yml
Labels: PR: Approval Required
