Repository pi-hole/docs, pull requests merged in 2021-04, with the labels that each got.

#490 Add scroll-up and dark mode to documentation
  docs/extra.css
  mkdocs.yml
Labels: PR: Approval Required, enhancement

#498 Update CI config
  .github/workflows/ci.yml
Labels: PR: Approved

#501 wireguard-dmks is not needed when running a sufficiently recent kernel
  docs/guides/vpn/wireguard/server.md
Labels: PR: Approval Required
