Repository pi-hole/docs, pull requests merged in 2022-12, with the labels that each got.

#812 Upate markdown_extensions
  docs/database/ftl.md
  docs/database/gravity/index.md
  docs/database/gravity/recovery.md
  docs/database/index.md
  docs/ftldns/blockingmode.md
  docs/ftldns/cache_dump.md
  docs/ftldns/compatibility.md
  docs/ftldns/compile.md
  docs/ftldns/configfile.md
  docs/ftldns/debugging.md
  docs/ftldns/dns-cache.md
  docs/ftldns/dns-resolver.md
  docs/ftldns/in-depth.md
  docs/ftldns/index.md
  docs/ftldns/interfaces.md
  docs/ftldns/package_dump.md
  docs/ftldns/privacylevels.md
  docs/ftldns/signals.md
  docs/ftldns/telnet-api.md
  docs/ftldns/valgrind.md
  docs/guides/misc/benchmark.md
  docs/guides/vpn/wireguard/client.md
  docs/guides/vpn/wireguard/overview.md
  docs/guides/vpn/wireguard/route-everything.md
  docs/guides/vpn/wireguard/server.md
  docs/index.md
  docs/main/basic-install.md
  docs/main/faq.md
  docs/main/origins.md
  docs/main/post-install.md
  docs/main/prerequisites.md
  docs/main/uninstall.md
  docs/main/update.md
  docs/regex/approximate.md
  docs/regex/overview.md
  docs/regex/pi-hole.md
  docs/regex/testmode.md
  docs/regex/tutorial.md
  docs/routers/asus.md
  mkdocs.yml
  requirements.txt
Labels: PR: Approval Required

#817 Add merge conflict workflow
  .github/workflows/merge-conflict.yml
Labels: PR: Approval Required

#825 Shorten no merge conflict message
  .github/workflows/merge-conflict.yml
Labels: PR: Approval Required, internal

#828 Fix admonitions
  docs/ftldns/blockingmode.md
  docs/ftldns/configfile.md
  docs/ftldns/valgrind.md
  docs/guides/dns/cloudflared.md
  docs/guides/misc/tor/dnssec.md
  docs/guides/misc/tor/performance-issues.md
  docs/guides/misc/tor/setup.md
  docs/guides/misc/tor/using-tor.md
  docs/guides/webserver/caddy.md
  docs/routers/fritzbox-de.md
  docs/routers/fritzbox.md
  docs/routers/ubiquiti-usg.md
Labels: PR: Approval Required

#827 Fritz!Box: assign DNS real-time priority and block bypassing DNS traffic
  docs/routers/fritzbox-de.md
  docs/routers/fritzbox.md
Labels: enhancement

#647 Create IPv6 guide for Fritz!Box routers
  docs/images/routers/fritzbox-ipv6-1-de.png
  docs/images/routers/fritzbox-ipv6-1.png
  docs/images/routers/fritzbox-ipv6-2-de.png
  docs/images/routers/fritzbox-ipv6-2.png
  docs/routers/fritzbox-de.md
  docs/routers/fritzbox.md
Labels: PR: Approval Required
