Repository pi-hole/docs, pull requests merged in 2022-07, with the labels that each got.

#734 Change FTL's default log file path from /var/log/pihole/pihole-FTL.log to /var/log/pihole/FTL.log
  docs/ftldns/configfile.md
  docs/ftldns/in-depth.md
  docs/regex/overview.md
Labels: For next release

#693 Add missing status types
  docs/database/ftl.md
Labels: PR: Approved, For next release

#719 Change lighttpd log file names
  docs/main/faq.md
Labels: PR: Approved, For next release

#725 Only DELAY_STARTUP within 60sec after boot
  docs/ftldns/configfile.md
Labels: PR: Approved, For next release

#727 Add interfaces API endpoint documentation
  docs/ftldns/telnet-api.md
Labels: PR: Approved, For next release

#696 Change default REPLY_WHEN_BUSY to drop
  docs/ftldns/configfile.md
Labels: PR: Approved, For next release

#379 Update log file location references
  docs/core/pihole-command.md
  docs/ftldns/cache_dump.md
  docs/ftldns/configfile.md
  docs/ftldns/dnsmasq_warn.md
  docs/ftldns/in-depth.md
  docs/regex/overview.md
Labels: PR: Approved, For next release

#740 Make group management more prominent
  docs/database/gravity/groups.md
  docs/group_management/example.md
  docs/group_management/groups.md
  docs/images/group_management/example-adlists-1.png
  docs/images/group_management/example-clients-1.png
  docs/images/group_management/example-clients-2.png
  docs/images/group_management/example-clients-3.png
  docs/images/group_management/example-domain-1.png
  docs/images/group_management/example-domain-2.png
  docs/images/group_management/example-domain-3.png
  docs/images/group_management/example-domain-4.png
  docs/images/group_management/example-domain-5.png
  docs/images/group_management/example-domain-6.png
  docs/images/group_management/example-groups.png
  docs/images/group_management/example-new-black.png
  docs/images/group_management/example-new-white.png
  mkdocs.yml
Labels: PR: Approved
