Repository pi-hole/docs, pull requests merged in 2022-10, with the labels that each got.

#781 Drop Fedora 34 and add 35 & 36
  docs/main/prerequisites.md
Labels: PR: Approval Required, For next release

#778 `PORTFILE` is deprecated
  docs/ftldns/configfile.md
Labels: For next release

#798 Slight update to Wireguard documentation
  docs/guides/vpn/wireguard/route-everything.md
Labels: PR: Approval Required
