Repository pi-hole/docs, pull requests merged in 2023-11, with the labels that each got.

#948 Update Node to 20
  .github/workflows/ci.yml
  docs/routers/ubiquiti-usg.md
Labels: PR: Approval Required

#947 Update Node to 20
  .github/workflows/ci.yml
  docs/routers/ubiquiti-usg.md
Labels: PR: Approval Required, Pi-hole v6.0

#950 Add authentication documentation
  docs/abbreviations.md
  docs/api/auth.md
  docs/api/index.md
  mkdocs.yml
Labels: Pi-hole v6.0
