Repository pi-hole/docs, pull requests merged in 2023-01, with the labels that each got.

#830 Add action to close stale PR
  .github/workflows/stale_pr.yml
Labels: internal

#840 Fix info field
  docs/ftldns/configfile.md
Labels: PR: Approval Required

#841 Add editorconfig and editorconfig-checker
  .editorconfig
  .github/workflows/editorconfig-checker.yml
  mkdocs.yml
  runtime.txt
Labels: PR: Approval Required, Internal

#835 Change labels in workflows
  .github/workflows/stale_pr.yml
Labels: PR: Approval Required, Internal

#823 update prerequisites to add Fedora 37 support
  docs/main/prerequisites.md
Labels: PR: Approved, For Next Release

#844 Remove Fedora 35
  docs/main/prerequisites.md
Labels: PR: Approved, For Next Release
